/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicios;
import java.util.Scanner;

public class Ex15 {
    public static void main(String[] args) {
        Scanner read = new Scanner(System.in);
        
        System.out.print("Informe um número: ");
        int numero = read.nextInt();
        
        if (numero >= 100 && numero <= 200) {
            System.out.println("O número está dentro do intervalo entre 100 e 200");
        } else {
            System.out.println("O número está fora do intervalo");
        }
        
    }
}
