/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio01POO;

public class App {
    public static void main(String[] args) {

        Pessoa p = new Pessoa();
        
        p.setNome("Renato");
        p.setAltura(1.68);
        
        p.imprimirDados();
    }
}
