/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio20;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {

        char opcaoMenu = 'S';
        float valorVeiculo;
        int anoVeiculo;
        float percentualDesconto;
        float valorDesconto;
        float valorAPagar;
        int totalVeiculosAte2000 = 0;
        float totalGeralVendas = 0;

        Scanner leitor = new Scanner(System.in);
        
        while (opcaoMenu == 'S' || opcaoMenu == 's') {
            System.out.print("Informe o valor do veículo: ");
            valorVeiculo = leitor.nextFloat();
            System.out.print("Informe o ano do veículo: ");
            anoVeiculo = leitor.nextInt();
            
            if (anoVeiculo <= 2000) {
                percentualDesconto = 0.12f;
                totalVeiculosAte2000++;
            } else {
                percentualDesconto = 0.07f;
            }

            valorDesconto = valorVeiculo * percentualDesconto;
            valorAPagar = valorVeiculo - valorDesconto;
            
            totalGeralVendas += valorAPagar;
            
            System.out.println("Desconto aplicado: " + (percentualDesconto * 100) + "% sobre R$ " + valorVeiculo + " = R$ " + valorDesconto);
            System.out.println("Valor final a pagar: R$ " + valorAPagar);
            
            System.out.println("Deseja inserir mais uma venda? [S] SIM / [N] NÃO");
            opcaoMenu = leitor.next().charAt(0);
        }
        
        System.out.println("Total de veículos até 2000 vendidos: " + totalVeiculosAte2000);
        System.out.println("Total da venda: R$" + totalGeralVendas);
        
    }
}
