/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicio24;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner leitor = new Scanner(System.in);
                
        int numero = 0;
        char desejaContinuar = 'S';
        
        while (desejaContinuar == 'S' || desejaContinuar == 's') {
            System.out.print("Digite um número: ");
            numero = leitor.nextInt();
            
            if (numero > 0) {
                System.out.println("Número positivo");
            } else if (numero < 0) {
                System.out.println("Número negativo");
            } else {
                System.out.println("Número ZERO");
            }
            
            System.out.println("Deseja continuar? [S] Sim / [N] Não");
            desejaContinuar = leitor.next().charAt(0);
            
        }
        
    }
}
