/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EstruturaEscolha;

public class App {
    public static void main(String[] args) {
        int codigo = 4;
        
        switch (codigo) {
            case 1:
                System.out.println("Bermuda");
                break;
            case 2:
                System.out.println("Calça");
                break;
            case 3:
                System.out.println("Camiseta");
                break;
            default:
                System.out.println("Não há produto cadastrado com esse código");
        }
    }
}
