/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Heranca;

import java.util.Date;

public class App {
    public static void main(String[] args) {

        Vendedor v = new Vendedor();
        Motorista m = new Motorista();
        
        v.setNome("Renato");
        v.setSalario(1000);
        v.setCpf("90090090090");
        v.setDataNascimento(new Date());
        
        v.setComissaoPorItem(2.50f);
        v.setTotalItensVendidos(72);
    
        
        System.out.println(v.calcularSalario());
    
    }
}
