/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EstruturaCondicionalSe;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
           
        Scanner read = new Scanner(System.in);
        
        System.out.print("Informe sua média final: ");
        float media = read.nextFloat();
        
        if (media == 10) {
            System.out.println("Parabéns, você foi aprovado com nota máxima!");
        } else if (media >= 7) {
            System.out.println("Parabéns, você foi aprovado!");
        } else {
            System.out.println("Infelizmente você foi reprovado...");
        }
        
    }
}
